# Generated by Django 3.1.1 on 2021-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210220_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='初期ユーザー', max_length=150, verbose_name='nickname'),
        ),
    ]
