# Generated by Django 3.1.1 on 2021-04-14 06:06

import authentication.models
import core.models
from django.db import migrations
import imagekit.models.fields
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20210406_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatar/default.jpg', null=True, upload_to=authentication.models.profile_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
