# Generated by Django 3.1.1 on 2021-02-17 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='brand name')),
                ('slug', models.CharField(max_length=50, verbose_name='brand slug')),
                ('official_site_link', models.CharField(max_length=255, verbose_name='brand link')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('slug', models.CharField(max_length=50, verbose_name='category slug')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
                ('slug', models.CharField(max_length=50, verbose_name='category slug')),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('description', models.TextField(verbose_name='description')),
                ('price_yen', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('image_src', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_link_to_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('rakuten_link_to_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_brand', to='pen.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_category', to='pen.category')),
                ('tag', models.ManyToManyField(related_name='pen_tag', to='pen.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('stars_of_design', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='design')),
                ('stars_of_durability', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='durability')),
                ('stars_of_usefulness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='usefulness')),
                ('stars_of_function', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='function')),
                ('stars_of_easy_to_get', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='easy_to_get')),
                ('good_point_text', models.TextField(blank=True, null=True)),
                ('bad_point_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_pen', to='pen.pen')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reviewer', 'pen')},
                'index_together': {('reviewer', 'pen')},
            },
        ),
        migrations.CreateModel(
            name='FavPen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fav_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav', to=settings.AUTH_USER_MODEL)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_fav', to='pen.pen')),
            ],
            options={
                'unique_together': {('fav_user', 'pen')},
                'index_together': {('fav_user', 'pen')},
            },
        ),
    ]
