# Generated by Django 3.1.1 on 2021-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(related_name='tag_pen', to='pen.Pen'),
        ),
    ]
