# Generated by Django 3.1.1 on 2021-02-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
