# Generated by Django 3.1.1 on 2021-02-20 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favpen',
            name='fav_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favpen',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faved', to='pen.pen'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='pen.pen'),
        ),
    ]
