# Generated by Django 3.1.1 on 2021-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0002_auto_20210214_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='pen',
            name='tag',
            field=models.ManyToManyField(related_name='pen_tag', to='pen.Tag'),
        ),
    ]
