# Generated by Django 3.1.1 on 2021-02-17 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0003_auto_20210216_0613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favpen',
            unique_together={('fav_user', 'pen')},
        ),
        migrations.AlterIndexTogether(
            name='favpen',
            index_together={('fav_user', 'pen')},
        ),
    ]
