# Generated by Django 3.1.1 on 2021-03-06 04:12

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0006_auto_20210223_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameModel(
            old_name='FavPen',
            new_name='FavProduct',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('description', models.TextField(verbose_name='description')),
                ('price_yen', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('image_src', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_link_to_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('rakuten_link_to_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='pen.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='pen.category')),
                ('tag', models.ManyToManyField(related_name='product_tag', to='pen.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='favproduct',
            name='product',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, related_name='faved', to='pen.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='pen.product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favproduct',
            unique_together={('fav_user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='favproduct',
            index_together={('fav_user', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='review',
            index_together={('reviewer', 'product')},
        ),
        migrations.RemoveField(
            model_name='favproduct',
            name='pen',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pen',
        ),
        migrations.DeleteModel(
            name='Pen',
        ),
    ]
