# Generated by Django 3.1.1 on 2021-03-06 05:47

import core.models
from django.conf import settings
from django.db import migrations
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0007_auto_20210306_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavProduct',
            new_name='Fav',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
