# Generated by Django 3.1.1 on 2021-03-11 04:28

import core.models
from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0010_auto_20210311_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='official_site_link',
            field=models.CharField(max_length=255, unique=True, verbose_name='brand link'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='brand slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='category slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='category slug'),
        ),
    ]
