# Generated by Django 3.1.1 on 2021-04-05 04:59

import core.models
from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0019_auto_20210404_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='pen.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='pen.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
