# Generated by Django 3.1.1 on 2021-04-12 13:52

import core.models
from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0031_auto_20210412_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='pen.Tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=core.models.ULIDField(db_index=True, default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
