# Generated by Django 3.2 on 2021-05-05 04:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('pen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='likeproduct',
            unique_together={('user', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='likepost',
            index_together={('user', 'post')},
        ),
        migrations.AlterIndexTogether(
            name='likeproduct',
            index_together={('user', 'product')},
        ),
    ]
